FLAGS = `sdl2-config --cflags --libs` -lSDL2 -lSDL2_mixer -lSDL2_image -lSDL2_ttf
NAME = dino

all:
	g++ $(NAME).cpp -o $(NAME) $(FLAGS)
	./$(NAME)

aula:
	rm aulaa
	g++ aula.cpp -o aulaa $(FLAGS)
	./aulaa